export enum AuthTypes {
  VERIFY_ADMIN_LOADING = "VERIFY_ADMIN_LOADING",
  VERIFY_ADMIN_SUCCESS = "VERIFY_ADMIN_SUCCESS",
  VERIFY_ADMIN_ERROR = "VERIFY_ADMIN_ERROR",
}

export enum LoginTypes {
  LOGIN_ADMIN_LOADING = "LOGIN_ADMIN_LOADING",
  LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS",
  LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR",
}
