export enum GetReportsTypes {
  GET_REPORTS_LOADING = "GET_REPORTS_LOADING",
  GET_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS",
  GET_REPORTS_ERROR = "GET_REPORTS_ERROR",
}

export enum GotRecentReportsTypes {
  GET_RECENT_REPORTS_LOADING = "GET_RECENT_REPORTS_LOADING",
  GET_RECENT_REPORTS_SUCCESS = "GET_RECENT_REPORTS_SUCCESS",
  GET_RECENT_REPORTS_ERROR = "GET_RECENT_REPORTS_ERROR",
}

export enum GotReportsReasonsTypes {
  GET_REPORTS_Reasons_LOADING = "GET_REPORTS_Reasons_LOADING",
  GET_REPORTS_Reasons_SUCCESS = "GET_REPORTS_Reasons_SUCCESS",
  GET_REPORTS_Reasons_ERROR = "GET_REPORTS_Reasons_ERROR",
}
