export enum GetReservationsTypes {
  GET_RESERVATIONS_LOADING = "GET_RESERVATIONS_LOADING",
  GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS",
  GET_RESERVATIONS_ERROR = "GET_RESERVATIONS_ERROR",
}
